import type { InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from 'styles/Home.module.css';

// This gets called on every request
export const getStaticProps = async () => {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api/hello`);

  return res.json().then((data: any) =>
    // Pass data to the page via props
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    ({ props: { data } }),
  );
};

const Home = ({ data }: InferGetStaticPropsType<typeof getStaticProps>) => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Hello World! <Link href="/profile/">Profile</Link>
      </h1>
      <p>
        {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          data?.name ?? 'Unknown'
        }
      </p>
    </main>
  </div>
);

export default Home;
