import Head from 'next/head';
import Link from 'next/link';
import styles from 'styles/Home.module.css';

const Home = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        two <Link href="/">home</Link>
      </h1>
      <p>おはようございますはじめてのNext.js</p>
    </main>
  </div>
);

export default Home;
